### PR TITLE
fix toc title chinese garbled code

### PR DESCRIPTION
**Pull request by wpjscc**

### CODE REVIEW

**Comment by LukeTowers** [comment]
Can you provide screenshots documenting the issue and fix?

**Comment by wpjscc** [comment]
before
image

after
image

**Comment by LukeTowers** [comment]
Thanks for the screenshot @wpjscc, we should be able to merge this shortly. Do you have a live link to where the Chinese version of the Winter CMS docs are living? I'm interested in exploring officially endorsed translations of our documentation, would love to be able to provide that on the main Winter CMS site itself :)

**Comment by bennothommo** [comment]
@wpjscc the `utf8_decode` method has been [deprecated as of PHP 8.2](https://www.php.net/utf8_decode), which means it shouldn't be relied on. I'm more interested in fixing the root cause of the UTF8 characters being mangled in the first place. I assume it might be because of either the Markdown parser or the DOMDocument reader that tries to extract the HTML elements.

**Comment by wpjscc** [comment]
> @wpjscc the `utf8_decode` method has been [deprecated as of PHP 8.2](https://www.php.net/utf8_decode), which means it shouldn't be relied on. I'm more interested in fixing the root cause of the UTF8 characters being mangled in the first place. I assume it might be because of either the Markdown parser or the DOMDocument reader that tries to extract the HTML elements.

You are right. Maybe he has problems when different languages are together. add `'<!DOCTYPE html><meta charset="UTF-8">'` before the content ,it work for me

ref: https://stackoverflow.com/questions/8218230/php-domdocument-loadhtml-not-encoding-utf-8-correctly

```
$dom = new \DOMDocument();

$content = '<!DOCTYPE html><meta charset="UTF-8">'.'<p> hello world chinese->中文</p>';

$dom->loadHTML($content);

$body = $dom->getElementsByTagName('body');
$body = $body->item(0);


echo $dom->saveHTML($body);
```
it output 
```
<body><p> hello world chinese-&gt;中文</p></body>
```
so ,it can solve In this way 

https://github.com/wintercms/wn-docs-plugin/compare/main...wpjscc:wn-docs-plugin:patch-1

**Comment by wpjscc** [comment]
> Thanks for the screenshot @wpjscc, we should be able to merge this shortly. Do you have a live link to where the Chinese version of the Winter CMS docs are living? I'm interested in exploring officially endorsed translations of our documentation, would love to be able to provide that on the main Winter CMS site itself :)

I am interested in this. Because translation takes a lot of time, it seems very good to use Google to translate documents in batches.

 
At present,  it is unstable, if can visit at https://docs.wpjs.cc/ 

The site source code is here https://github.com/wpjscc/docs

**Comment by LukeTowers** [comment]
Thanks for the information @wpjscc, I'll close this in favour of #18. @bennothommo please review when you get a moment.

**Comment by bennothommo** [comment]
Those docs look great @wpjscc :)

**Pull request closed without merging**
